apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-job
  namespace: selfhosted
spec:
  template:
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        args:
          - clone
          - --depth=1
          - --single-branch
          - --branch=main
          - https://github.com/Dhanush1219/azureselfhostedagent.git
          - /workspace
        volumeMounts:
          - name: kaniko-workspace
            mountPath: /workspace

      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--dockerfile=/Dockerfile"
          - "--context=/workspace"
          - "--destination=hardikpoc.azurecr.io/kaniko-build:v1"
        volumeMounts:
          - name: kaniko-workspace
            mountPath: /workspace
      volumes:
        - name: kaniko-workspace
          emptyDir: {}
      restartPolicy: Never
